const dados = {
    _id: 1,
    lista_cronograma: [
      {
        mes_cronograma: "Mes 1",
        ordem_mes_cronograma: 1,
        niveis: [
          {
            tipo: "projeto",
            ordem_nivel: "1",
            nome_nivel: "Beelieve",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "subprojeto",
            ordem_nivel: "1.1",
            nome_nivel: "Frontend",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "nivelsubprojeto",
            ordem_nivel: "1.1.1",
            nome_nivel: "Design",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "subprojeto",
            ordem_nivel: "1.2",
            nome_nivel: "Backend",
            id_nivel: 2,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "nivelsubprojeto",
            ordem_nivel: "1.2.1",
            nome_nivel: "BD",
            id_nivel: 2,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
        ],
      },
      {
        mes_cronograma: "Mes 2",
        ordem_mes_cronograma: { $numberInt: "2" },
        niveis: [
          {
            tipo: "projeto",
            ordem_nivel: "1",
            nome_nivel: "Beelieve",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "subprojeto",
            ordem_nivel: "1.1",
            nome_nivel: "Frontend",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "nivelsubprojeto",
            ordem_nivel: "1.1.1",
            nome_nivel: "Design",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "subprojeto",
            ordem_nivel: "1.2",
            nome_nivel: "Backend",
            id_nivel: 2,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "nivelsubprojeto",
            ordem_nivel: "1.2.1",
            nome_nivel: "BD",
            id_nivel: 2,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
        ],
      },
      {
        mes_cronograma: "Mes 3",
        ordem_mes_cronograma: { $numberInt: "3" },
        niveis: [
          {
            tipo: "projeto",
            ordem_nivel: "1",
            nome_nivel: "Beelieve",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "subprojeto",
            ordem_nivel: "1.1",
            nome_nivel: "Frontend",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "nivelsubprojeto",
            ordem_nivel: "1.1.1",
            nome_nivel: "Design",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "subprojeto",
            ordem_nivel: "1.2",
            nome_nivel: "Backend",
            id_nivel: 2,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "nivelsubprojeto",
            ordem_nivel: "1.2.1",
            nome_nivel: "BD",
            id_nivel: 2,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
        ],
      },
      {
        mes_cronograma: "Mes 4",
        ordem_mes_cronograma: { $numberInt: "4" },
        niveis: [
          {
            tipo: "projeto",
            ordem_nivel: "1",
            nome_nivel: "Beelieve",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "subprojeto",
            ordem_nivel: "1.1",
            nome_nivel: "Frontend",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "nivelsubprojeto",
            ordem_nivel: "1.1.1",
            nome_nivel: "Design",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "subprojeto",
            ordem_nivel: "1.2",
            nome_nivel: "Backend",
            id_nivel: 2,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "nivelsubprojeto",
            ordem_nivel: "1.2.1",
            nome_nivel: "BD",
            id_nivel: 2,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
        ],
      },
      {
        mes_cronograma: "Mes 5",
        ordem_mes_cronograma: { $numberInt: "5" },
        niveis: [
          {
            tipo: "projeto",
            ordem_nivel: "1",
            nome_nivel: "Beelieve",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "subprojeto",
            ordem_nivel: "1.1",
            nome_nivel: "Frontend",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "nivelsubprojeto",
            ordem_nivel: "1.1.1",
            nome_nivel: "Design",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "subprojeto",
            ordem_nivel: "1.2",
            nome_nivel: "Backend",
            id_nivel: 2,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "nivelsubprojeto",
            ordem_nivel: "1.2.1",
            nome_nivel: "BD",
            id_nivel: 2,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
        ],
      },
      {
        mes_cronograma: "Mes 6",
        ordem_mes_cronograma: { $numberInt: "6" },
        niveis: [
          {
            tipo: "projeto",
            ordem_nivel: "1",
            nome_nivel: "Beelieve",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "subprojeto",
            ordem_nivel: "1.1",
            nome_nivel: "Frontend",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "nivelsubprojeto",
            ordem_nivel: "1.1.1",
            nome_nivel: "Design",
            id_nivel: 1,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "subprojeto",
            ordem_nivel: "1.2",
            nome_nivel: "Backend",
            id_nivel: 2,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
          {
            tipo: "nivelsubprojeto",
            ordem_nivel: "1.2.1",
            nome_nivel: "BD",
            id_nivel: 2,
            progresso_planejado: 0.0,
            progresso_real: 0.0,
          },
        ],
      },
    ],
  }